### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by RichardLitt** [opensourcecities/tokyo#1]
This list should not be solely in English. Can we find a way to have a Japanese language version, as well? Would the best way be to have two lists and sync them, or to include the Japanese and English side by side?

**Comment by sotayamashita** [comment]
> Would the best way be to have two lists and sync them ...

I am developing the [GitLocalize](https://github.com/marketplace/gitlocalize) and it helps people to keep up to date translation docs though GitHub Flow. Vue.js and Nuxt.js are using our tool now.

However, I do not think we need translation at the moment. Before translating, we need to improve template and other stuff.

**Comment by RichardLitt** [comment]
That is a really cool tool. Alright, closing this then! Good luck. Let me know if I can help more.
