### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by ronkorving** [opensourcecities/tokyo#8]
Hi there,

If you are looking for volunteer maintainers on opensourcecities/tokyo, I wouldn't mind signing up :)
Please let me know if that is interesting to you and if you need any information from me.

よろしくお願いします

**Comment by RichardLitt** [comment]
Works for me. @sotayamashita? 

We need to add some users and projects! @ronkorving - want to add yourself and some of your favorite projects first?

**Comment by ronkorving** [comment]
Already shamelessly added those of the company I work for in #7, but I will definitely try to add more :)

Adding myself is not very interesting, because all my Open Source work is under the company's organization. Unless we just want to maintain a list of people in Tokyo who are active in Open Source? In that case, I can add myself.

**Comment by RichardLitt** [comment]
> Unless we just want to maintain a list of people in Tokyo who are active in Open Source? In that case, I can add myself.

Yep.

**Comment by sotayamashita** [comment]
@ronkorving 

>Works for me. @sotayamashita?

Sound good to me. 

> We need to add some users and projects! @ronkorving - want to add yourself and some of your favorite projects first?

I agree with him.

**Comment by RichardLitt** [comment]
@sotayamashita Add yourself too! 😅

**Comment by ronkorving** [comment]
I've advertised [on Twitter](https://twitter.com/ronkorving/status/912514947757727744)
